### ISSUE TITLE
Fails to build on Windows using Python 3.10 + Fix

### ISSUE THREAD

**Issue by AlphonsG** [cheind/py-lapsolver#17]
Fails with `py-lapsolver\pybind11\include\pybind11/numpy.h(35,22): error C2065: 'ssize_t': undeclared identifier`.

Checking out the master branch of the pybind11 submodule, instead of the currently set branch [v2.2](https://github.com/cheind/py-lapsolver/blob/69f6e55efe1c1cd2e30139cc68c49e20a4fc3f49/.gitmodules#L4), fixes the error and the build finishes. All tests passed.

**Comment by cheind** [comment]
ah nice, thanks for letting me know. Will hopefully update soon.

**Comment by AlphonsG** [comment]
No problem mate, thanks.

**Comment by cheind** [comment]
bumped again to latest
